config/routes.rb
AhcJbDemo::Application.routes.draw do
  resources :jobs

  resources :users

  root :to => "jobs#index"

end

app/models/job.rb
class Job < ActiveRecord::Base
  attr_accessible :area, :department, :description, :location, :title, :job_type, :user_id
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :phone
  has_many :jobs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @jobs }
    end
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    @job = Job.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @job }
    end
  end

  # GET /jobs/new
  # GET /jobs/new.json
  def new
    @job = Job.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @job }
    end
  end

  # GET /jobs/1/edit
  def edit
    @job = Job.find(params[:id])
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(params[:job])

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render json: @job, status: :created, location: @job }
      else
        format.html { render action: "new" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /jobs/1
  # PUT /jobs/1.json
  def update
    @job = Job.find(params[:id])

    respond_to do |format|
      if @job.update_attributes(params[:job])
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job = Job.find(params[:id])
    @job.destroy

    respond_to do |format|
      format.html { redirect_to jobs_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	# Returns full title on a per-page basis.
	def full_title(page_title)
		base_title = "Academic Health Center"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end

end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :job_type %><br />
    <%= f.text_field :job_type %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :area %><br />
    <%= f.text_field :area %>
  </div>
  <div class="field">
    <%= f.label :department %><br />
    <%= f.text_field :department %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<% provide(:title, 'Edit Job') %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

<h1>Editing job</h1>

<%= render 'form' %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<% provide(:title, 'Job Postings') %>

<!-- Search Box -->
<form action="" method="get" id="searchform">

    <div class="search-wrap">

        <div>
            <input type="text" id="search" title="" name="s" class="text" placeholder="All Jobs" value="" />
            <input type="text" id="near" title="Location" name="location" class="text" placeholder="Location" value="" />
            <label for="search"><button type="submit" title="Go" class="submit">Go</button></label>

            <input type="hidden" name="ptype" value="job_listing" />
        </div>

        <!-- <div class="radius">
            <label for="radius">Radius:</label>
            <select name="radius" class="radius">
                <option value="1" >1 mi</option>
                <option value="5" >5 mi</option>
                <option value="10" >10 mi</option>
                <option value="50"  selected='selected'>50 mi</option>
                <option value="100" >100 mi</option>
                <option value="1000" >1,000 mi</option>
                <option value="5000" >5,000 mi</option>
            </select>
        </div>
 -->
    </div><!-- end search-wrap -->

</form>

<div class="clear"></div>

<h2 class="pagetitle">
    <small class="rss"><a href=""><img src="/assets/img/feed.png" title="Latest Jobs RSS Feed" alt="Latest Jobs RSS Feed" /></a></small>
    Latest Jobs 
</h2>


<form class="filter" method="get" action="">
    <p><input type="checkbox" name="profession" id="profession" checked="checked" value="show" /> <label for="profession">Professional</label></p>
    <p><input type="checkbox" name="student" id="student" checked="checked" value="show" /> <label for="student">Student Worker</label></p>
    <p><input type="checkbox" name="graduate" id="graduate" checked="checked" value="show" /> <label for="graduate">Graduate</label></p>
    <!-- <p><input type="checkbox" name="scholar" id="scholar" checked="checked" value="show" /> <label for="scholar">Scholarship</label></p> -->
    <p><input type="checkbox" name="post-doc" id="post-doc" checked="checked" value="show" /> <label for="post-doc">Post-Doctoral</label></p>
    <p><input type="checkbox" name="volunteer" id="volunteer" checked="checked" value="show" /> <label for="volunteer">Volunteer</label></p>
    <p><input type="checkbox" name="internship" id="internship" checked="checked" value="show" /> <label for="internship">Internship</label></p>
    <p><input type="checkbox" name="part-time" id="part-time" checked="checked" value="show" /> <label for="part-time">Part-Time</label></p>
    <p>
    <input type="submit" value="Filter" class="submit" />
    <input type="hidden" name="action" value="Filter" />
    </p>
    <div class="clear"></div>
</form>


<ol class="jobs">
    <% @jobs.each do |job| %>
    <li class="job">
        <dl>

            <dt>Type</dt>
            <dd class="type"><span class="jtype <%= job.job_type %>"><%= job.job_type %></span></dd>

            <dt>Job</dt>
            <dd class="title">
                <strong><%= link_to job.title, job %></strong>
                <a href="" rel="nofollow"><%= job.area %></a>&ndash; Posted by <a href=""><%= job.department %></a>
            </dd>
            
            <dt>Location</dt>
            <dd class="location"><strong><%= job.location %></strong>United States</dd>

            <dt>Date Posted</dt>
            <dd class="date"><strong>May 15</strong> <span class="year">2013</span></dd>
        </dl>
    </li>
    <% end %>
</ol>

<!-- <table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Location</th>
    <th>Area</th>
    <th>Department</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @jobs.each do |job| %>
  <tr>
    <td><%= job.title %></td>
    <td><%= job.description %></td>
    <td><%= job.location %></td>
    <td><%= job.area %></td>
    <td><%= job.department %></td>
    <td><%= job.user_id %></td>
    <td><%= link_to 'Show', job %></td>
    <td><%= link_to 'Edit', edit_job_path(job) %></td>
    <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br /> -->

app/views/jobs/new.html.erb
<% provide(:title, 'New Job') %>

<%= link_to 'Back', jobs_path %>

<h1>New job</h1>

<%= render 'form' %>

app/views/jobs/show.html.erb
<% provide(:title, @job.title) %>

<p id="notice"><%= notice %></p>

<div class="section single">

  <div class="section_header">

    <div class="date"><strong>May 15</strong> <span class="year">2013</span></div>

    <h1 class="title">
      <span class="type"><span class="jtype <%= @job.job_type %>"><%= @job.job_type %></span></span>
      <%= @job.title %>
    </h1>

    <p class="meta">
      <a href="" rel="nofollow"><%= @job.area %></a> &ndash; Posted by <a href=""><%= @job.department %></a>
      &ndash;<strong><%= @job.location %></strong>, United States
    </p>
    <div class="clear"></div>

  </div><!-- end section_header -->

  <div class="section_content">

    <!-- <p class="sharethis">
    <span class="st_twitter_hcount" displayText="Tweet"></span>
    <span class="st_facebook_hcount" displayText="Share"></span>
    </p> -->

    <h2>Job Description</h2>

    <%= simple_format(@job.description) %>

    <section id="listing-fields"></section>

    <!-- <h2>How to Apply</h2>
    Etiam molestie quam id lacus tempus facilisis id vel enim. In dapibus ante ac felis aliquam mollis. Pellentesque eget magna nec erat sodales facilisis ut dictum dui. Aliquam erat volutpat. Maecenas tellus massa, sollicitudin quis vehicula id, fringilla id massa. Proin non urna in risus accumsan dapibus. Morbi non turpis tellus, vitae varius dui. Sed ultricies sem vel arcu ultricies laoreet. Ut sed sapien at erat faucibus facilisis. Donec pulvinar purus et risus pretium hendrerit. Donec dui tellus, aliquet facilisis volutpat vel, imperdiet at libero. Curabitur nisi nunc, mattis sed consequat sit amet, tempor a enim. -->

    <p>&nbsp;</p>    
    <p class="meta"><em>Job Categories: <a href=''>thisCat</a>. Job Types: <a href=''>thisType</a>. Job Tags: <a href=''>tag1</a>, <a href=''>tag2</a>, and <a href=''>tag3</a>. Job expires in <strong>x days</strong>.</em></p>

    <p class="stats">0 total views, 0 today</p> 
    <div class="clear"></div>

  </div><!-- end section_content -->


  <div id="apply_form" class="section_content ">
    <h2>Apply for this Job</h2>
    <form action="" method="post" class="main_form" enctype="multipart/form-data">

      <p><label for="your_name">Name <span title="required">*</span></label> <input type="text" class="text" name="your_name" id="your_name" value=" " /> </p>
      <p><label for="your_email">Email <span title="required">*</span></label> <input type="text" class="text" name="your_email" id="your_email" value="" /></p>
      <p><label for="your_message">Message <span title="required">*</span></label> <textarea rows="5" cols="30" name="your_message" id="your_message"></textarea></p>

      <p class="optional"><label for="your_cv">Upload resum&eacute; (pdf, doc, txt, rtf)</label> <input type="file" class="text" name="your_cv" id="your_cv" /></p>
      <p class="optional"><label for="your_coverletter">Upload cover letter (pdf, doc, txt, rtf)</label> <input type="file" class="text" name="your_coverletter" id="your_coverletter" /></p>

      <p><input type="submit" class="submit" name="apply_to_job" value="Apply for Job" /></p>

  </form>
  </div>

<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %> |

</div>






<!-- <p>
  <b>Title:</b>
  <%= @job.title %>
</p>

<p>
  <b>Description:</b>
  <%= @job.description %>
</p>

<p>
  <b>Location:</b>
  <%= @job.location %>
</p>

<p>
  <b>Area:</b>
  <%= @job.area %>
</p>

<p>
  <b>Department:</b>
  <%= @job.department %>
</p>

<p>
  <b>User:</b>
  <%= @job.user_id %>
</p> -->

app/views/layouts/application.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<link rel="shortcut icon" href="/assets/img/favicon.ico" type="image/x-icon" />

<!-- jquery core -->
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

<script type="text/javascript">
	var g_strLanguageId = "en";
</script>
<script type="text/javascript" src="/assets/js/wcm.toggle.js"></script>

<link rel="stylesheet" href="/assets/css/css_ahc_global.css" type="text/css" />
<link rel="stylesheet" href="/assets/css/css_ahc_page_home.css" type="text/css" />
<link rel="stylesheet" href="/assets/css/css_ahc_sliders.css" type="text/css">
<link rel="stylesheet" href="/assets/css/css_ahc_jobboard.css" type="text/css">
<script type="text/javascript" src="/assets/js/js_ahc_global.js"></script>

<style type="text/css">
@font-face{
	font-family: 'TitilliumText15L400wt';
	src: url('http://ahc-test.umn.edu/ahcdemo/prod/groups/ahc/@sec/@ahc/documents/asset/font_ctsi_titillium_400_eot.eot');
	src: url('http://ahc-test.umn.edu/ahcdemo/prod/groups/ahc/@sec/@ahc/documents/asset/font_ctsi_titillium_400_woff.woff') format('woff'),
		url('http://ahc-test.umn.edu/ahcdemo/prod/groups/ahc/@sec/@ahc/documents/asset/font_ctsi_titillium_400_ttf.ttf') format('truetype'),
		url('http://ahc-test.umn.edu/ahcdemo/prod/groups/ahc/@sec/@ahc/documents/asset/font_ctsi_titillium_400_svg.svg') format('svg');
	font-weight: normal;
	font-style: normal;
}
</style> 
<title><%= full_title(yield(:title)) %></title>
<link href="assets/css/login-container.css" media="all" rel="stylesheet" type="text/css" />
</head>
<!--[if lt IE 7 ]> <body class="ie6"> <![endif]--> 
<!--[if IE 7 ]>    <body class="ie7"> <![endif]--> 
<!--[if IE 8 ]>    <body class="ie8"> <![endif]--> 
<!--[if IE 9 ]>    <body class="ie9"> <![endif]--> 
<!--[if gt IE 9]>  <body>             <![endif]-->  
<!--[if !IE]><!--> 
<body>	<!--<![endif]-->

<div style="text-align:center;">
	<div id="umheader">
		<div class="center clearfix">
        	<div class="ir">
            	<a href="" class="no_external">Main navigation</a> | 
            	<a href="" class="no_external">Main content</a>
        	</div>
	        <div class="campus_links">
	            <ul>
	            <li>Campuses:</li>
	            <li><a href="http://www.umn.edu" class="no_external">Twin Cities</a></li>
	            <li><a href="http://www.crk.umn.edu" class="no_external">Crookston</a></li>
	            <li><a href="http://www.d.umn.edu" class="no_external">Duluth</a></li>
	            <li><a href="http://www.morris.umn.edu" class="no_external">Morris</a></li>
	            <li><a href="http://www.r.umn.edu" class="no_external">Rochester</a></li>
	            <li><a href="http://www.umn.edu/campuses.php" class="no_external">Other Locations</a></li>
	            </ul>
	        </div>
    	</div>
	    <div class="maroonStripe">
	        <div class="center clearfix">
	            <div class="logo_uofm">
	                <a href="http://www.umn.edu/" class="no_external">Go to the U of M home page</a>
	            </div>
	            <div class="search_area clearfix">
	                <div class="search_nav clearfix">
	                    <a href="http://onestop.umn.edu/" class="no_external btn_onestop">OneStop</a>
	                    <a href="https://www.myu.umn.edu/" class="no_external btn_myu">myU</a>
	                </div>
	                <div class="search">
	                	<form name="gsearch" id="gsearch" class="gsearch" action="http://search.umn.edu/s/" method="GET" title="Search Websites and People">
			            	<label for="search_field">Search Websites and People</label>
			            	<input type="text"   value="Search Websites and People" name="q" id="search_field" title="Search text" onblur="if (this.value=='') this.value='Search Websites and People'" onfocus="if (this.value=='Search Websites and People') this.value=''"/> 
			            	<input type="image" class="search_btn" value="Search" alt="Submit Search" src="http://a.umn.edu/img/search_button-001.gif" />
			            	<input type="hidden" value="www.med.umn.edu"		 name="r" />
			            	<input type="hidden" value="eAHC"					 name="e" />
			        	</form>
			        	<script type="text/javascript">
			        		var gsearch = document.forms.gsearch;
			        		var inputs	= {};
			        		for(var i=0; i<gsearch.length; i++) if(gsearch[i].id || gsearch[i].name)
			        			inputs[gsearch[i].id || gsearch[i].name] = i;
			        		gsearch[inputs.r].value = location.host;
			        	</script>
	                </div>
	            </div>
	        </div>
	    </div>
	</div><!-- end header -->
	<div class="clear"></div>
		
	<div id="main_container" class="container">
	
		<!-- RED TAB AT TOP OF THE HEADER -->		
		<div class="container">
			<div class="more_info clearfix">
				<ul class="clearfix">
				<li id="red_tab_1"><a href="http://www.health.umn.edu/">Academic Health Center</a></li>
				</ul>
			</div>
		</div>

		<!-- CONTENTS OF THE HEADER -->		
		<div class="dept_title clearfix">
			<h4>Academic Health Center</h4>
			<h2>Job Board Prototype</h2>
			<!-- <h3></h3> -->
		</div>



		<!-- SIDE BAR -->
		<div class="main_content clearfix">
			<div class="sidebar">
				<h3></h3>
				<!-- <ul class="sidebar_nav">
					<li>TEST</li>
				</ul> -->

				<%= link_to 'Submit a Job', new_job_path, :class => 'sidebar_button no_external' %>
				<!-- <a href="" class="sidebar_button no_external">Submit a Job</a> -->


				<ul class="sidebar_subnav">
    				<li>
    					<a href="">Schools &amp; Programs</a>
    					<ul>
    						<li>School of Dentistry</li>
    						<li>Medical School</li>
    						<li>School of Nursing</li>
    						<li>College of Pharmacy</li>
    						<li>School of Public Health</li>
    						<li>College of Veterinary Medicine</li>
    					</ul>
    				</li>
		    		<li>
		    			<a href="">Date Posted</a>
		    			<ul>
		    				<li>Today</li>
		    				<li>This Week</li>
		    				<li>Last Week</li>
		    				<li>This Month</li>
		    			</ul>
		    		</li>
				</ul> 
	
			</div>
		
			<!--#####################################################-->
			<div class="content">
				<h3 class="content_title">AHC Job Postings</h3>

				<%= yield %>

			</div>
			<!--#####################################################-->
		</div>
						

		<div id="footer">
			<div class="container clearfix">
				<!-- <span class="span4">
					<ul class="footer_links">
						<li><strong><a href="http://www.health.umn.edu/facultystaff/communications/index.htm" class="no_external">Office of Communications</a></strong></li>
						<li><a href="http://health.umn.edu/" target="">Academic Health Center</a><br /><a target="" href="mailto:ahcweb@umn.edu">ahcweb@umn.edu</a> | 612-624-5100<br />420 Delaware Street SE<br /> A-395 Mayo Memorial Building<br /> Minneapolis, MN 55455&nbsp;</li>
					</ul>
				</span>

				<span class="span3">
					<ul class="footer_links">
						<li><strong>
								Getting started
						</strong></li>
						
							<li><a href="../../../../../../../prod/groups/ahc/contact/schedule-a-consultation/index.htm" class="no_external">Schedule a consultation</a></li>
							<li><a href="http://z.umn.edu/webform" class="no_external">Request a project</a></li>
							<li><a href="../../../../../../../prod/groups/ahc/prod/groups/ahc/@pub/@ahc/documents/content/ahc_content_411544.pdf" class="no_external">Web info session (PDF)</a></li>
							<li><a href="../../../../../../../prod/groups/ahc/prod/groups/ahc/@pub/@ahc/documents/content/ahc_content_412714.pdf" class="no_external">Process checklist (PDF)</a></li>
							<li><a href="../../../../../../../prod/groups/ahc/about/creative-agency-services/index.htm" class="no_external">Creative Agency services</a></li>
						
					</ul>
				</span> -->
			</div>
		</div>


		<div id="umfooter">
			<div class="center">
		        <div class="copy">
		            <ul>
		                <li>&copy;2013 Regents of the University of Minnesota. All rights reserved.</li>
		                <li>The University of Minnesota is an equal opportunity educator and employer</li>
		                
		            </ul>
		        </div>
		        <div class="resourceLinks">
		            <ul class="footer_links">
		                <li>Twin Cities Campus:</li>
		                <li><a href="http://www1.umn.edu/pts/" class="no_external">Parking &amp; Transportation</a></li>
		                <li><a href="http://www.umn.edu/twincities/maps/index.html" class="no_external">Maps &amp; Directions</a></li>
		            </ul>
		            <ul class="footer_links">
		            	<li><a href="http://www.directory.umn.edu/" class="no_external">Directories</a></li>
		                <li><a href="http://www.umn.edu/twincities/contact/" class="no_external">Contact U of M</a></li>
		                <li><a href="http://www.privacy.umn.edu/" class="no_external">Privacy</a></li>
		            </ul> 
		        </div>
		    </div>
		</div>
			
	</div>
</div>
	
</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Phone</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.phone %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Phone:</b>
  <%= @user.phone %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>